# A use case to switch a module stream from ruby:2.5 to ruby:2.6.
ARG BASE_IMAGE=fedora:30
FROM ${BASE_IMAGE}

# ====
# Step 0: Create the prerequisites

# Create a testing user.
RUN useradd -m tester
WORKDIR /work
COPY . .
RUN chown -R tester:tester /work

# Install ruby:2.5 module.
RUN yum -y module reset ruby
RUN yum -y module enable ruby:2.5
RUN yum -y module install ruby:2.5

# Install gem packages by gem command on Ruby 2.5.
# to test gem packages that have C-extention.
# byebug and nio4r gem packages are C-extention gem.

# Install dependencies for the installed gem packages.
RUN yum -y install \
  gcc \
  make \
  ruby-devel \
  rubygem-rdoc \
  redhat-rpm-config

USER tester
RUN ruby -v
RUN gem -v
RUN gem install byebug -v 11.0.1 --user-install
RUN gem install gem2rpm -v 1.0.1 --user-install
RUN gem install nio4r -v 2.5.1 --user-install
RUN gem list byebug gem2rpm nio4r
RUN ls ~/.gem/ruby/gems/

# ====
# Step 1: Run the following command to determine if your system is prepared
# for switching to a later stream
USER root
RUN yum -y distro-sync

# ====
# Step 2: Change the active stream to the later one
RUN yum -y module reset ruby
RUN yum -y module enable ruby:2.6

# ====
# Step 3: Synchronize installed packages to perform the change between streams
# "yum distro-sync" can be error without --allowerasing option.
RUN yum -y distro-sync || true
RUN yum -y --allowerasing distro-sync

# Prepare to test.
USER tester
RUN ruby -v
RUN gem -v
