# A use case to switch a module stream.
# The default is the use case from ruby:2.5 to ruby:2.6.
ARG BASE_IMAGE=fedora:30
FROM ${BASE_IMAGE}

ARG MODULE_NAME=ruby
# Current stream
ARG CUR_STREAM=2.5
# New stream
ARG NEW_STREAM=2.6
ARG MODULE_PROFILE
# YUM repository file URL
ARG YUM_REPO_URL

ENV MODULE_NAME "${MODULE_NAME}"
ENV CUR_STREAM "${CUR_STREAM}"
ENV NEW_STREAM "${NEW_STREAM}"
ENV MODULE_PROFILE "${MODULE_PROFILE}"

# ====
# Step 0: Create the prerequisites

# Create a testing user.
RUN useradd -m tester
WORKDIR /work
COPY . .
RUN chown -R tester:tester /work

# Install YUM repository file if it exists.
RUN script/run-install-repo.sh

# Install current module.
RUN yum module list "${MODULE_NAME}"
RUN yum -y module reset "${MODULE_NAME}"
RUN yum -y module enable "${MODULE_NAME}:${CUR_STREAM}"
# Run yum moudle install considering an existance of the module profile.
RUN script/run-module-install.sh

# Install RPM packages or language packages (in case of ruby, gem packages)
# for testing.
# Some points to be tested.
# * RPM packages depending on current module stream,
#   but not depending on new module stream.
# * Language packages depending on current module stream,
#   but not depending on new module stream.

# Install dependencies by root user.
RUN script/run install-deps-root.sh

USER tester
# Install dependencies by regular user.
RUN script/run install-deps-user.sh

# ====
# Step 1: Run the following command to determine if your system is prepared
# for switching to a later stream
USER root
RUN yum -y distro-sync

# ====
# Step 2: Change the active stream to the later one
RUN yum -y module reset "${MODULE_NAME}"
RUN yum -y module enable "${MODULE_NAME}:${NEW_STREAM}"

# ====
# Step 3: Synchronize installed packages to perform the change between streams
# "yum distro-sync" can be error without --allowerasing option.
RUN yum -y distro-sync || true
RUN yum -y --allowerasing distro-sync

RUN yum module list "${MODULE_NAME}"

# Prepare to test.
USER tester
RUN script/run prepare-to-test.sh

CMD script/run test.sh
